name: Deploy to Server

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    # 1. Checkout the repository
    - name: Checkout Repository
      uses: actions/checkout@v3

    # 2. Set up Node.js environment
    - name: Set up Node.js
      uses: actions/setup-node@v3
      with:
        node-version: 18

    # 3. Install dependencies
    - name: Install Dependencies
      run: npm install

    # 4. Build the application
    - name: Build Application
      run: npm run build

    # 5. Add SSH Key to SSH Agent
    - name: Add SSH Key
      uses: webfactory/ssh-agent@v0.5.3
      with:
        ssh-private-key: ${{ secrets.SERVER_SSH_KEY }}

    # 6. Deploy to server via SSH
    - name: Deploy to Server
      uses: appleboy/ssh-action@v0.1.3
      with:
        host: ${{ secrets.SERVER_HOST }}
        username: ${{ secrets.SERVER_USER }}
        port: 22
        script: |
          cd /var/www/QuillTrack
          git pull origin main
          npm install
          npm run build
          pm2 restart QuillTrack
