name: Deploy to Server

on:
  workflow_run:
    workflows: ["CodeQL Security Analysis (TypeScript)"]
    branches: [main]
    types: [completed]

jobs:
  deploy:
    runs-on: ubuntu-latest
    # Solo ejecutar si el análisis CodeQL fue exitoso
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    
    steps:
    - uses: actions/checkout@v4  # Actualizado a v4
    
    - name: Setup SSH
      run: |
        mkdir -p ~/.ssh/
        echo "${{ secrets.SERVER_SSH_KEY }}" > ~/.ssh/deploy_key
        chmod 600 ~/.ssh/deploy_key
        eval "$(ssh-agent -s)"
        ssh-add ~/.ssh/deploy_key
        
    - name: Deploy
      run: |
        ssh -o StrictHostKeyChecking=no -i ~/.ssh/deploy_key ${{ secrets.SERVER_USER }}@${{ secrets.SERVER_HOST }} '
        cd /var/www/QuillTrack &&
        git pull origin main &&
        npm install &&
        npm run build &&
        pm2 restart QuillTrack
        '